# For more information:
# https://laravel.com/docs/sail
# https://hub.docker.com/_/mysql
# https://hub.docker.com/_/phpmyadmin
# https://hub.docker.com/r/axllent/mailpit

services:
  app:
    build:
      context: ../../.
      dockerfile: docker/development/Dockerfile
      args:
        BASE_IMAGE_NAME: '${BASE_IMAGE_NAME}'
        WWWGROUP: '${WWWGROUP}'
    image: '${APP_IMAGE_NAME:-app:latest}'
    restart: on-failure
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${APP_PORT_SSL:-443}:443'
      - '${SUPERVISOR_PORT:-9001}:9001'
    environment:
      TZ: '${TZ:-UTC}'
      WWWUSER: '${WWWUSER}'
      SUV_WEB_SERVER: '${SUV_WEB_SERVER:-true}'
      SUV_SCHEDULER: '${SUV_SCHEDULER:-false}'
      SUV_SCHEDULER_NUMPROCS: '${SUV_SCHEDULER_NUMPROCS:-1}'
      SUV_WORKER: '${SUV_WORKER:-false}'
      SUV_WORKER_NUMPROCS: '${SUV_WORKER_NUMPROCS:-1}'
    volumes:
      - '../../:/var/www/html'
      - '../../docker/no/virtual:/var/www/html/docker'
      - '../../docker/no/logs/php:/var/log/php'
      - '../../docker/no/logs/nginx:/var/log/nginx'
      - '../../docker/no/logs/supervisor:/var/log/supervisor'
    networks:
      - compose_project_network
    depends_on:
      - mysql
      - mailpit

  mysql:
    image: 'mysql:${DB_IMAGE_TAG:-latest}'
    #platform: linux/amd64
    restart: on-failure
    ports:
      - '${DB_PORT_FORWARD:-3306}:3306'
    environment:
      MYSQL_ROOT_HOST: '${DB_ROOT_HOST:-%}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '${DB_ALLOW_EMPTY_ROOT_PASSWORD:-yes}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-}'
      #MYSQL_RANDOM_ROOT_PASSWORD: '${DB_RANDOM_ROOT_PASSWORD:-yes}'
      MYSQL_LOCALHOST_USER: '${DB_LOCALHOST_USER:-yes}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      TZ: '${TZ}'
    volumes:
      - '../../docker/container/mysql/development/init:/docker-entrypoint-initdb.d'
      - '../../docker/container/mysql/development/conf.d:/etc/mysql/conf.d'
      - '../../docker/no/mysql/data:/var/lib/mysql'
      - '../../docker/no/logs/mysql:/var/log/mysql'
    command: [ 'mysqld', '--character-set-server=${DB_CHARACTER_SET:-utf8mb4}', '--collation-server=${DB_COLLATION:-utf8mb4_general_ci}' ]
    # '--default-authentication-plugin=mysql_native_password'
    networks:
      - compose_project_network
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-u', 'root', '-p${DB_ROOT_PASSWORD:-}' ]
      interval: 5s # Interval between health checks.
      timeout: 5s  # Timeout for each health checking.
      retries: 3   # Hou many times retries.

  phpmyadmin:
    hostname: 'phpmyadmin'
    image: 'phpmyadmin:${PMA_IMAGE_TAG:-latest}'
    restart: on-failure
    ports:
      - '${PMA_PORT_FORWARD:-8080}:80'
    environment:
      PMA_HOST: 'mysql'
      PMA_PORT: '3306'
      #PMA_USER: '${DB_USERNAME}'
      #PMA_PASSWORD: '${DB_PASSWORD}'
      MAX_EXECUTION_TIME: '${PMA_MAX_EXECUTION_TIME:-300}'
      MEMORY_LIMIT: '${PMA_MEMORY_LIMIT:-512M}'
      UPLOAD_LIMIT: '${PMA_UPLOAD_MAX_FILESIZE:-128M}'
      TZ: '${TZ}'
    volumes:
      - '../../docker/no/logs/phpmyadmin:/var/log/apache2'
    networks:
      - compose_project_network
    depends_on:
      - mysql

  mailpit:
    image: 'axllent/mailpit:${MAILPIT_IMAGE_TAG:-latest}'
    restart: on-failure
    ports:
      - '${MAILPIT_SMTP_PORT_FORWARD:-1025}:1025'
      - '${MAILPIT_WEB_PORT_FORWARD:-8025}:8025'
    environment:
      TZ: '${TZ}'
    networks:
      - compose_project_network

networks:
  compose_project_network:
    driver: bridge
    name: '${COMPOSE_PROJECT_NETWORK:-compose_project_network}'
