<?php

namespace App\Http\Requests\Front\Boilerplate;

use App\Http\Requests\Core\BaseWebFormRequest;

/**
 * Class DemoFrontRequest
 *
 * @package App\Http\Requests\Front\Boilerplate
 */
class DemoFrontRequest extends BaseWebFormRequest
{
    /**
     * Prepare the data for validation.
     *
     * @return void
     */
    protected function prepareForValidation(): void
    {
        // TODO: Change the autogenerated stub
        $inputs = $this->all();
        if (isset($inputs['sort'])) {
            // Set 'sort' to lower
            $this->merge(['sort' => strtolower($this->get('sort'))]);
        }
        if (isset($inputs['sort_type'])) {
            // Set 'sort_type' to upper
            $this->merge(['sort_type' => strtoupper($this->get('sort_type'))]);
        }
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(): array
    {
        // TODO: Change the autogenerated stub
        return parent::rules();
    }

    /**
     * Get custom messages for validator errors.
     *
     * @return array
     */
    public function messages(): array
    {
        // TODO: Change the autogenerated stub
        return parent::messages();
    }

    /**
     * Handle a passed validation attempt.
     *
     * @return void
     */
    protected function passedValidation(): void
    {
        $defaultData = [];

        // TODO: Change the autogenerated stub

        $this->mergeDataPassedValidation($defaultData);
    }
}