<?php

namespace App\Providers;

use App\Repositories\Contracts\IUserRepo;
use App\Repositories\UserRepo;
use Illuminate\Support\ServiceProvider;

/**
 * Class RepositoryServiceProvider
 *
 * @package App\Providers
 */
class RepositoryServiceProvider extends ServiceProvider
{
    /**
     * Register bindings in the container.
     *
     * @return void
     */
    public function boot(): void
    {
        //
    }

    /**
     * Register services.
     *
     * @return void
     */
    public function register(): void
    {
        $this->registerAuthBindings();
        // TODO: Change the autogenerated stub
    }

    /**
     * Auth module binding
     */
    private function registerAuthBindings(): void
    {
        $this->app->bind(
            IUserRepo::class,
            UserRepo::class
        );
    }

}
