<?php

namespace App\Jobs\Boilerplate;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

/**
 * Class ProcessDemo
 *
 * @package App\Jobs\Boilerplate
 */
class ProcessDemo implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     */
    public function __construct()
    {
        // TODO: Change the autogenerated stub
    }

    /**
     * Execute the job.
     */
    public function handle(): void
    {
        // TODO: Change the autogenerated stub
    }
}
